global:
  checkNewVersion: false
  sendAnonymousUsage: false
log:
  level: DEBUG
api:
  dashboard: true
  insecure: true # Do not use in production
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
certificateResolvers:
  letsencrypt:
    acme:
      email: "your_email@provider.com"
      storage: "/var/traefik/certs/cloudflare-acme.json"
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false